// Shared colors/fonts + a couple of small draw helpers used by every scene,
// mirroring the palette that used to live in src/style.css.

import Phaser from "phaser";
import type { CardCategory } from "../model/cardTypes.ts";

export const COLORS: {
  background: number;
  panel: number;
  card: Record<CardCategory, number>;
  ultimate: number;
  ultimateHover: number;
  restart: number;
  restartHover: number;
  meterTrack: number;
  meterFill: number;
} = {
  background: 0x1e2230,
  panel: 0x2a2f42,
  card: {
    attack: 0xb5423a,
    defend: 0x2f6f8f,
    buff: 0x3a8f5a,
    debuff: 0x6a4a94,
  },
  ultimate: 0xa8842f,
  ultimateHover: 0xc49b3a,
  restart: 0x4a5573,
  restartHover: 0x586694,
  meterTrack: 0x1b1f2c,
  meterFill: 0xa8842f,
};

export const TEXT: { body: string; muted: string; white: string } = {
  body: "#e8eaf0",
  muted: "#a9adc1",
  white: "#ffffff",
};

export const FONT_FAMILY = "system-ui, -apple-system, 'Segoe UI', sans-serif";

// --- Crisp rendering on high-DPI / scaled-up screens ----------------------
//
// Every scene lays itself out in a fixed 1280x720 coordinate space. If the
// canvas were also 1280x720 pixels, Scale.FIT would stretch it up to fill the
// window -- and on a Retina/HiDPI screen (devicePixelRatio 2+) that stretch
// is what made text and icons look blurry. Instead the canvas is created
// RENDER_SCALE times bigger and each scene's camera is zoomed by the same
// factor (useRenderScale below), so all the layout code keeps using 1280x720
// coordinates while the actual pixels match the screen.

export const GAME_WIDTH = 1280;
export const GAME_HEIGHT = 720;

function computeRenderScale(): number {
  const dpr = window.devicePixelRatio || 1;
  // How much Scale.FIT will enlarge the 960x760 layout to fill the window.
  const fitRatio = Math.max(1, Math.min(window.innerWidth / GAME_WIDTH, window.innerHeight / GAME_HEIGHT));
  // Capped at 3: beyond that the extra pixels aren't visible but cost memory.
  return Phaser.Math.Clamp(Math.ceil(dpr * fitRatio), 1, 3);
}

export const RENDER_SCALE = computeRenderScale();

// Call first thing in every scene's create(): zooms the camera so the
// 1280x720 layout fills the RENDER_SCALE-sized canvas, anchored top-left.
export function useRenderScale(scene: Phaser.Scene): void {
  scene.cameras.main.setOrigin(0, 0).setZoom(RENDER_SCALE);
}

// --- Scene backgrounds ------------------------------------------------------
//
// Full-screen illustrations from public/backgrounds/ (generated by
// scripts/backgrounds.js). Rasterized at up to 2x the layout size so they
// stay sharp when the camera is zoomed; if one fails to load, the scene just
// keeps its plain background color.

export interface BackgroundDef {
  key: string;
  file: string;
}

export const BACKGROUNDS: { classSelect: BackgroundDef; battle: BackgroundDef } = {
  classSelect: { key: "bg-class-select", file: "class-select.svg" },
  battle: { key: "bg-battle", file: "battle.svg" },
};

// Call from a scene's preload().
export function preloadBackground(scene: Phaser.Scene, bg: BackgroundDef): void {
  if (scene.textures.exists(bg.key)) return;
  const scale = Math.min(RENDER_SCALE, 2);
  scene.load.svg(bg.key, `${import.meta.env.BASE_URL}backgrounds/${bg.file}`, {
    width: GAME_WIDTH * scale,
    height: GAME_HEIGHT * scale,
  });
}

// Call first thing in create(), so everything else draws on top of it.
export function addBackground(scene: Phaser.Scene, bg: BackgroundDef): Phaser.GameObjects.Image | null {
  if (!scene.textures.exists(bg.key)) return null;
  return scene.add.image(0, 0, bg.key).setOrigin(0, 0).setDisplaySize(GAME_WIDTH, GAME_HEIGHT);
}

// A soft drop shadow for text drawn straight on a background illustration.
export function textShadow<T extends Phaser.GameObjects.Text>(text: T): T {
  return text.setShadow(0, 2, "#000000", 6, false, true) as T;
}

// A filled rounded rectangle, its origin at (0,0) like every other Phaser
// shape, with an interactive hit area covering the same rect -- the click
// target for anything drawn with this (class cards, hand cards, buttons).
export function roundedRect(
  scene: Phaser.Scene,
  w: number,
  h: number,
  color: number,
  radius = 12
): Phaser.GameObjects.Graphics {
  const g = scene.add.graphics();
  g.fillStyle(color, 1);
  g.fillRoundedRect(0, 0, w, h, radius);
  g.setInteractive(new Phaser.Geom.Rectangle(0, 0, w, h), Phaser.Geom.Rectangle.Contains);
  return g;
}

export interface ButtonOptions {
  color: number;
  hoverColor: number;
  onClick: () => void;
}

export interface Button {
  container: Phaser.GameObjects.Container;
  setEnabled: (enabled: boolean) => void;
}

// A rounded-rect button with a centered label and hover/disabled handling.
// Returns { container, setEnabled } -- setEnabled(false) dims it and drops
// its interactivity, matching the CSS `:disabled` cards/buttons this
// replaces.
export function createButton(
  scene: Phaser.Scene,
  x: number,
  y: number,
  w: number,
  h: number,
  text: string,
  { color, hoverColor, onClick }: ButtonOptions
): Button {
  const container = scene.add.container(x, y);

  const bg = scene.add.graphics();
  const draw = (fill: number): void => {
    bg.clear();
    bg.fillStyle(fill, 1);
    bg.fillRoundedRect(0, 0, w, h, 8);
  };
  draw(color);
  bg.setInteractive(new Phaser.Geom.Rectangle(0, 0, w, h), Phaser.Geom.Rectangle.Contains);

  const label = scene.add
    .text(w / 2, h / 2, text, { fontFamily: FONT_FAMILY, fontSize: "14px", color: TEXT.white })
    .setOrigin(0.5);

  container.add([bg, label]);
  container.setData("enabled", true);

  bg.on("pointerover", () => container.getData("enabled") && draw(hoverColor));
  bg.on("pointerout", () => container.getData("enabled") && draw(color));
  bg.on("pointerdown", () => container.getData("enabled") && onClick());

  function setEnabled(enabled: boolean): void {
    container.setData("enabled", enabled);
    container.setAlpha(enabled ? 1 : 0.45);
    draw(color);
    if (enabled) bg.setInteractive(new Phaser.Geom.Rectangle(0, 0, w, h), Phaser.Geom.Rectangle.Contains);
    else bg.disableInteractive();
  }

  return { container, setEnabled };
}
