// Print SQL that upserts the local catalog (src/model/catalogData.js) into
// the Supabase catalog tables. Run with `npm run catalog:sql`, e.g.
//
//   npm run catalog:sql > supabase/migrations/<timestamp>_seed_game_catalog.sql
//
// Upserts only: rows that exist in the database but not in catalogData.js
// are left alone.

import { LOCAL_CATALOG_ROWS } from "../src/model/catalogData.js";

// Column order per table, and which columns are jsonb.
const TABLES = [
  { name: "synergies", key: ["id"], columns: ["id", "name", "description", "counts_category", "tiers"], json: ["tiers"] },
  {
    name: "classes",
    key: ["id"],
    columns: ["id", "name", "base_stats", "ultimate", "passives", "sort_order"],
    json: ["base_stats", "ultimate", "passives"],
  },
  { name: "cards", key: ["id"], columns: ["id", "name", "category", "props"], json: ["props"] },
  { name: "class_synergies", key: ["class_id", "synergy_id"], columns: ["class_id", "synergy_id"], json: [] },
  { name: "class_deck_cards", key: ["class_id", "card_id"], columns: ["class_id", "card_id", "copies"], json: [] },
];

const quote = (text) => `'${String(text).replaceAll("'", "''")}'`;

function literal(value, isJson) {
  if (isJson) return `${quote(JSON.stringify(value))}::jsonb`;
  if (value === null || value === undefined) return "null";
  if (typeof value === "number") return String(value);
  return quote(value);
}

const out = [
  "-- Generated by `npm run catalog:sql` from src/model/catalogData.js.",
  "-- Initial contents of the game catalog tables (see *_game_catalog.sql).",
  "",
];

for (const table of TABLES) {
  const rows = LOCAL_CATALOG_ROWS[table.name];
  const values = rows.map((row) => `  (${table.columns.map((c) => literal(row[c], table.json.includes(c))).join(", ")})`);
  const updates = table.columns.filter((c) => !table.key.includes(c));
  const onConflict = updates.length
    ? `on conflict (${table.key.join(", ")}) do update set\n  ${updates.map((c) => `${c} = excluded.${c}`).join(",\n  ")}`
    : `on conflict (${table.key.join(", ")}) do nothing`;
  out.push(`insert into public.${table.name} (${table.columns.join(", ")}) values\n${values.join(",\n")}\n${onConflict};`, "");
}

process.stdout.write(out.join("\n"));
