-- Generated by `npm run catalog:sql` from src/model/catalogData.js.
-- Initial contents of the game catalog tables (see *_game_catalog.sql).

insert into public.synergies (id, name, description, counts_category, tiers) values
  ('bulwark', 'Bulwark (example)', 'Placeholder synergy: rewards playing defend cards.', 'defend', '[{"count":2,"effects":[{"kind":"stat_modifier","stat":"def","mode":"flat","amount":5}]},{"count":4,"effects":[{"kind":"stat_modifier","stat":"def","mode":"flat","amount":12}]}]'::jsonb),
  ('kindling', 'Kindling (example)', 'Placeholder synergy: aggression (attack cards) fuels ultimate charge.', 'attack', '[{"count":2,"effects":[{"kind":"stat_modifier","stat":"ur","mode":"flat","amount":2}]},{"count":4,"effects":[{"kind":"stat_modifier","stat":"ur","mode":"flat","amount":5}]}]'::jsonb)
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  counts_category = excluded.counts_category,
  tiers = excluded.tiers;

insert into public.classes (id, name, base_stats, ultimate, passives, sort_order) values
  ('guardian', 'Guardian (example)', '{"hp":44,"def":6,"mr":2,"er":2,"ur":6,"crit":0}'::jsonb, '{"id":"guardian_ultimate","name":"TBD","description":"Placeholder -- ultimate name/theme is still an open question.","cost":24,"damage":14}'::jsonb, '[]'::jsonb, 1),
  ('pyromancer', 'Pyromancer (example)', '{"hp":34,"def":2,"mr":3,"er":4,"ur":8,"crit":0}'::jsonb, '{"id":"pyromancer_ultimate","name":"TBD","description":"Placeholder -- ultimate name/theme is still an open question.","cost":20,"damage":18}'::jsonb, '[]'::jsonb, 2)
on conflict (id) do update set
  name = excluded.name,
  base_stats = excluded.base_stats,
  ultimate = excluded.ultimate,
  passives = excluded.passives,
  sort_order = excluded.sort_order;

insert into public.cards (id, name, category, props) values
  ('shield_bash', 'Shield Bash', 'attack', '{"damageType":"physical","value":6}'::jsonb),
  ('heavy_slam', 'Heavy Slam', 'attack', '{"damageType":"physical","value":9}'::jsonb),
  ('iron_wall', 'Iron Wall', 'defend', '{"damageType":"physical","mode":"flat","amount":5,"stacking":"nonstackable","duration":1}'::jsonb),
  ('brace', 'Brace', 'defend', '{"damageType":"physical","mode":"percent","amount":0.3,"stacking":"nonstackable","duration":2}'::jsonb),
  ('second_wind', 'Second Wind', 'buff', '{"effects":[{"kind":"energy_regen","mode":"flat","amount":2}],"duration":3}'::jsonb),
  ('taunt', 'Taunt', 'debuff', '{"effects":[{"kind":"meter_siphon","amount":5}],"duration":1}'::jsonb),
  ('ember_dart', 'Ember Dart', 'attack', '{"damageType":"element","value":5}'::jsonb),
  ('fire_lance', 'Fire Lance', 'attack', '{"damageType":"element","value":8}'::jsonb),
  ('heat_shroud', 'Heat Shroud', 'defend', '{"damageType":"element","mode":"flat","amount":4,"stacking":"nonstackable","duration":1}'::jsonb),
  ('stoke_the_flame', 'Stoke the Flame', 'buff', '{"effects":[{"kind":"energy_regen","mode":"flat","amount":3}],"duration":2}'::jsonb),
  ('scorch', 'Scorch', 'debuff', '{"effects":[{"kind":"stat_modifier","stat":"er","mode":"flat","amount":-2}],"duration":2}'::jsonb)
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  props = excluded.props;

insert into public.class_synergies (class_id, synergy_id) values
  ('guardian', 'bulwark'),
  ('pyromancer', 'kindling')
on conflict (class_id, synergy_id) do nothing;

insert into public.class_deck_cards (class_id, card_id, copies) values
  ('guardian', 'shield_bash', 4),
  ('guardian', 'heavy_slam', 3),
  ('guardian', 'iron_wall', 4),
  ('guardian', 'brace', 3),
  ('guardian', 'second_wind', 2),
  ('guardian', 'taunt', 2),
  ('pyromancer', 'ember_dart', 4),
  ('pyromancer', 'fire_lance', 3),
  ('pyromancer', 'heat_shroud', 3),
  ('pyromancer', 'stoke_the_flame', 3),
  ('pyromancer', 'scorch', 3)
on conflict (class_id, card_id) do update set
  copies = excluded.copies;
